document.getElementById("cont").onclick = function() {
    document.getElementById("form").innerHTML = 'At Paddleboat Technical Assurance, we pride ourselves on our engagement with the tech-savvy community. To work at Paddleboat Technical Assurance is to be knowledgeable of these communities, and to represent Paddleboat Technical Assurance\'s signature values and customer service experience at all times.<br><br>Please enter your Jazzmin account name. If you do not have a Jazzmin account, please contact our Application Assistance workers at (719) 567-6742 to be directed to a labor application.<br><br><br><div class="center"><div class="block"><label for="jazzminacc">@</label><input type="text" class="field" id="jazzminacc" style="width:10em;"></div></div>';
    document.getElementById("cont").onclick = function() {
        document.getElementById("form").innerHTML = '<div class="center"><div class="block">Please explain the gap in your online activity between <b>September 2035</b> and <b>June 2037</b>.<br><br><textarea class="longtext"></textarea></div></div>';
        document.getElementById("cont").onclick = function() {
            document.getElementById("form").innerHTML = '<div class="center"><div class="block">Please explain the loss of <b>219</b> followers in <b>Spring 2039</b>.<br><br><textarea class="longtext"></textarea></div></div>';
            document.getElementById("cont").onclick = function() {
                document.getElementById("form").innerHTML = '<div class="center"><div class="block">Please explain the like/share/comment ratio on the following Jazzmin post made <b>August 28, 2033</b>.<br><br>"had to sit next to this guy for four hours i swear you never see these guys on united"<br><span style="font-size:0.75em;color:#606060;">(Image failed to load. This may be because you are not connected to the internet, or the original media was deleted.)</span><br><br><textarea class="longtext" style="height:12em;"></textarea></div></div>'
                document.getElementById("cont").onclick = function() {
                    document.getElementById("main").innerHTML = '<div class="card" style="height:auto;">It looks like you are missing one or more Paddleboat Community Engagement Requirements. Please visit our site to learn more, and to find a comprehensive list of these Requirements.<br><br>The Paddleboat Community Engagement Requirements exist to ensure quality of service and community engagement. Our Engagement Requirements are what allow us to provide our signature Paddleboat customer service experience. To ensure the utmost quality of customer service and service interactions, Paddleboat Technical Assurance must require these Engagement Requirements be met by all new employees. Please fullfill any and all missing Engagement Requirements before applying again, or contact our Application Assistance workers at (719) 567-6742 or @PTAapphelp on Jazzmin to be assigned to a labor position.<br><br>We look forward to bringing you on board!</div>';
                };
            };
        };
    };
};